config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  get '/logout', to: 'sessions#destroy'
  post '/logout', to: 'sessions#destroy'

  resources :completed_stories
  resources :templates
  resources :users

  get '/categories', to: 'templates#categoryindex', as: 'categories'
  get '/categories/:category', to: 'templates#categoryshow', as: 'category'
  patch '/completed_stories/:id/rate', to: 'completed_stories#rate'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/completed_story.rb
class CompletedStory < ApplicationRecord
  belongs_to :template
  belongs_to :user

  def self.insert_words(template_instance, words_array)
    story = template_instance.story_template

    words_array.each do |key,value|
      key = "##{key}#"
      story.sub! key, value
    end
    #returns string of story filled in with user submissions "The fat lady went to...."
    story
  end

  def self.random_story
    num = CompletedStory.count - 1
    CompletedStory.all[rand(0..num)]
  end

  def self.story_from_popular_template
    most_popular_template = Template.most_popular_template

    num = most_popular_template.completed_stories.count - 1
    most_popular_template.completed_stories[num]
  end





end

app/models/template.rb
class Template < ApplicationRecord
  belongs_to :user
  has_many :completed_stories
  validates :title, :story_template, presence: true
  validates :title, :story_template, uniqueness: true
  validate :select_key_words

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/


######## VALIDATOR METHOD ##############

  def select_key_words
    if story_template.count("#") < 2
      errors.add(:story_template, "Must select at least one key word by adding a hashtag to either end of the selected word. Ex. '#keyword#'.")
    end
  end

#########################################


  def find_key_words
    hash = {}
    key_words = self.story_template.scan(/#(.*?)#/).flatten
    #returns array of all key words stripped of "#". ex: "adjective_1"

    key_words.each do |key|
      hash[key] = nil
    end
    hash
  end

  def self.categories
    categories = []

    Template.all.each do |template|
      categories << template.category
    end
    categories.uniq
  end


  def calculate_average_rating
    array_ratings = self.completed_stories.map {|completed_story| completed_story.temp_rating}

    if !array_ratings.first
      return nil
    else
      sum_ratings = array_ratings.inject(0){|sum,x| sum + x }
      sum_ratings/array_ratings.count
    end
  end

  def self.random_template

    if self.count == 1
      self.first
    else
      byebug
      num = Template.count - 1
      self.all[rand(0..num)]
    end
  end

  def self.rated_templates
    self.all.select do |template|
      template.avg_rating != nil
    end
  end

  def self.most_popular_template
    self.rated_templates.sort_by do |template|
      template.avg_rating
    end.last
  end


end





# <%= form_tag '/completed_stories' do %>
#   <% count = 0 %>
#   <% @hash.each do |key,value| %>
#     <%= label_tag :"#{key}:" %>
#     <%= text_field_tag :"words[#{key}]" %>
#     <% count += 1 %>
#     <% if count % 4 == 0 %>
#         <br>
#       <% end %>
#     <% end %>
#     <br><br>
#     <%= hidden_field_tag(:template_id, @template.id) %>
#     <%= submit_tag "Create Story" %>
# <% end %>

app/models/user.rb
class User < ApplicationRecord
  has_many :templates
  has_many :completed_stories
  has_secure_password

  validates :name, uniqueness: true
  validates :name, presence: true

  has_attached_file :avatar, styles: {
    medium: "300x300>",
    thumb: "100x100>"
  }
      
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  before_action :current_user

  def current_user
    @user = (User.find_by(id: session[:user_id]) || User.new)
  end

  def logged_in?
    current_user.id != nil
  end

  def require_logged_in
    return redirect_to(controller: 'sessions', action: 'new') unless logged_in?
  end



end

app/controllers/completed_stories_controller.rb
class CompletedStoriesController < ApplicationController
  before_action :require_logged_in

  def new
  end

  def create
    @template = Template.find_by(id: params[:template_id])
    @finished_story = CompletedStory.insert_words(@template, params[:words])
    @completed_story = CompletedStory.new(user_id: current_user.id, template_id: @template.id, finished_story: @finished_story)

    if @completed_story.valid?
      @completed_story.save
    else
      render template_path(@template)
    end
    redirect_to @completed_story
  end

  def index
    @completed_stories = CompletedStory.all
  end

  def show
    @completed_story = CompletedStory.find(params[:id])
  end

  def update
    @completed_story = CompletedStory.find(params[:id])
    @completed_story.temp_rating = params[:completed_story][:temp_rating]
    @completed_story.save


    avg_rating = @completed_story.template.calculate_average_rating

    @completed_story.template.avg_rating = avg_rating
    @completed_story.template.save

    flash[:success] = "Great! You gave '#{@completed_story.template.title}' a rating of #{params[:completed_story][:temp_rating]}"
    render :show
    
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
   user = User.find_by(name: params[:user][:name])
   user = user.try(:authenticate, params[:user][:password])

   return redirect_to(controller: 'sessions', action: 'new') unless user

   session[:user_id] = user.id
   @user = user
   redirect_to controller: 'welcome', action: 'home'
  end

  def destroy
   session.delete :user_id
   redirect_to '/'
  end

end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
before_action :require_logged_in

  def index
    @templates = Template.all
  end

  def show
    @template = Template.find_by(id: params[:id])
    @hash = @template.find_key_words
  end

  def categoryindex
    @categories = Template.categories
    @templates = Template.all
  end

  def categoryshow
    @templates = Template.all.select do |each_story|
       each_story.category == params[:category]
      end

    @category = params[:category]
  end

  def edit
    @template = Template.find(params[:id])
  end

  def update
    @template = Template.find(params[:id])

    if @template.update(template_params)
      redirect_to category_path(template_params[:category])
    else
      render :edit
    end
  end

  def new
    @template = Template.new
  end

  def create
    @template = Template.new(template_params)
    @template.user_id = current_user.id

    if @template.valid?
      @template.save
      redirect_to category_path(template_params[:category])
    else
      render :new
    end
  end

  private

  def template_params
    params.require(:template).permit(:title, :story_template, :category, :rating, :avatar)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    #User signup
    @user = User.new(user_params)

    if @user.valid?
      return redirect_to controller: 'users', action: 'new' unless @user.save
      session[:user_id] = @user.id
      redirect_to controller: 'welcome', action: 'home'
    else
      render :new
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    render :layout => "application"
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :avatar)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :require_logged_in
  

  def home
    @templates = Template.all
    @random_template = Template.random_template
    @most_popular_template = Template.most_popular_template
    @story_from_pop_temp = CompletedStory.story_from_popular_template
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/completed_stories_helper.rb
module CompletedStoriesHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/completed_stories/index.html.erb
<div class="container">
<div class="jumbotron" style="background:transparent url(/assets/background.jpg) no-repeat center /cover">
  <center><h1>All Submitted Stories</h1></center>
</div>
</div>

<!--You can access a completed_stories title by going through template. Ex. @completed_story.template.title   -->
<!--The below should be a grid with the html elements teh headers and the erb tags rendering below the headers  -->

<br>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">STORY NAME</th>
        <th scope="col">ORIGINALLY WRITTEN BY</th>
        <th scope="col">WRITTEN ON</th>
        <th scope="col">CATEGORY</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <% @completed_stories.each do |completed_story| %>
         <td><%= link_to completed_story.template.title, completed_story_path(completed_story) %></td>
         <td><%= link_to completed_story.template.user.name, user_path(completed_story.template.user) %></td>
         <td><%= completed_story.template.created_at %></td>
         <td><%= link_to completed_story.template.category, category_path(completed_story.template.category) %></td>
         </tr>
        <% end %>
    </tbody>
  </table>

app/views/completed_stories/show.html.erb
<div class="container">
  <div class="jumbotron" style="background:transparent url(https://s3.amazonaws.com/madlibs-assets/assets/images/background.jpg) no-repeat center /cover">


    <%= image_tag @completed_story.template.avatar.url(:medium) %>
    <h2><%= @completed_story.template.title  %></h2>
    <h4>Written by: <%= @completed_story.template.user.name  %></h2>
    <h4>Submitted by: <%= @completed_story.user.name  %></h2>
    <p>Date submitted: <%= @completed_story.created_at.strftime('%B %d, %G') %></p>

    <p><%= @completed_story.finished_story %></p>
    <br>
  </div>
</div>

<% if !@completed_story.temp_rating %>
  <p>Give this story a rating from 1 to 5 (5 being the funnest story you've ever filled out):</p>

  <%= form_for(@completed_story) do |f| %>
    <%= f.select :temp_rating, [['1', 1], ['2', 2], ['3', 3], ['4',4], ['5',5]] %>
    <%= f.submit 'Rate Story' %>
  <% end %>
<% else %>
  <%= flash[:success] %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>MADLIBS!</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
  <link rel="stylesheet" href="/assets/application.css"/>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
  <!--- STYLING -->


<nav class="navbar navbar-default" >
  <div class="container-fluid" >
    <ul class="nav navbar-nav">
      <li><%= link_to "HOME", "/"  %></li>
      <li><%= link_to "PLAY MADLIBS", categories_path  %></li>
      <li><%= link_to "CREATE A MADLIBS STORY", new_template_path  %></li>
      <li><%= link_to "READ PAST SUBMISSIONS", completed_stories_path  %></li>
      <li><%= link_to "VIEW PROFILE", user_path(current_user) %></li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <li><a href="/logout"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
    </ul>

  </div>
</nav>


<div class="container">
  <br>
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Madlibs</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="/assets/sessions.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
  <style>
  /* body {background-color: blanchedalmond;} */

  </style>


<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
    </div>

    <ul class="nav navbar-nav navbar-right">
      <li><a href="/users/new"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>

<div class="container">
  <div class="jumbotron" style="background:transparent url(/assets/background.jpg) no-repeat center /cover">
    <h1 style="color:midnightblue;">MADLIBS!</h1>
    <p style="color:midnightblue;"> Play madlibs, create your own stories, see other user's stories.</p>
  </div>


  <div class="row">
    <div class="col-sm-4"><%= yield %></div>
    <div class="col-sm-8">
      <div class="row well">
        <div class="col-sm-4"><%=image_tag("https://s3.amazonaws.com/madlibs-assets/assets/images/oparh_winfrey.jpeg", size:"150x188")%></div>
        <div class="col-sm-8 text-right"><h4>"Pintpoint your butt." <br><br> - Oprah Winfrey</h4></div>
      </div>

      <div class="row well">
        <div class="col-sm-8 text-right"><h4>"Secretary of State Rex Tillerson was reported to have called the president a “butthead”." <br><br> - Tobias Funke</h4></div>
        <div class="col-sm-4 text-right"><%= image_tag("https://s3.amazonaws.com/madlibs-assets/assets/images/tobias_funke.jpg", size:"150x188") %></div>
      </div>

      <div class="row well">
        <div class="col-sm-4"><%= image_tag("https://s3.amazonaws.com/madlibs-assets/assets/images/aladdin.jpeg", size:"150x188") %></div>
        <div class="col-sm-8 text-right"><h4>"It might be worth a little experimenting to see for yourself whether your num chuck game improves following sex." <br><br> - Aladdin</h4></div>
      </div>

      <div class="row well">
        <div class="col-sm-8 text-right"><h4>"There is tremendous jelly beans in just being Tom Cruise." <br><br> - Nicolas Cage</h4></div>
        <div class="col-sm-4 text-right"><%= image_tag("https://s3.amazonaws.com/madlibs-assets/assets/images/nicolas_cage.jpg", size:"150x188") %></div>
      </div>
    </div>
  </div>
</div>



</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">MADLIBS!</a>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to "Play MADLIBS", categories_path  %></li>
      <li><%= link_to "Create a MADLIBS story", new_template_path  %></li>
      <li><%= link_to "Read all user's completed stories", completed_stories_path %></li>
      <li><%= link_to "See all users", users_path %> </li>
      <li><%= link_to "View Account", user_path(@user) %></li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <li><a href="/logout"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
    </ul>
  </div>
</nav>


<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/templates/categoryindex.html.erb
<div class="container">
  <div class="jumbotron" style="background:transparent url(/assets/background.jpg) no-repeat center /cover">
    <h1>Choose a Story Category</h1><br>



<h3>
<div class="container">
  <div class="row">
    <div class="col-sm-3 well text-center"> <%= link_to"Self Help", category_path("Self Help")%></div>
    <div class="col-sm-1 text-center"></div>
    <div class="col-sm-3 well text-center"><%= link_to "History", category_path("History")%></div>
    <div class="col-sm-1 text-center"></div>
    <div class="col-sm-3 well text-center"><%= link_to "Police Blotter", category_path("Police Blotter")%></div>
  </div>
  <div class="row">
    <div class="col-sm-3 well text-center"><%= link_to "Nursery Rhyme", category_path("Nursery Rhyme")%></div>
    <div class="col-sm-1  text-center"></div>
    <div class="col-sm-3 well text-center"><%= link_to "How-To", category_path("How-To")%></div>
    <div class="col-sm-1  text-center"></div>
    <div class="col-sm-3 well text-center"><%= link_to "Politics", category_path("Politics")%></div>
  </div>
</div>
</h3>

</div>
</div>

app/views/templates/categoryshow.html.erb
<div class="container">
  <div class="jumbotron" style="background:transparent url(/assets/background.jpg) no-repeat center /cover">
    <h1>Choose a Story</h1>
    <h3><%= @category %> // <%= link_to"Choose another category", categories_path%> </h3>

  </div>
  </div>

    <br>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">TITLE</th>
            <th scope="col">AUTHOR</th>
            <th scope="col">AVERAGE RATING</th>
            <th scope="col">DATE CREATED</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <% @templates.each do |template| %>
             <td><%= link_to template.title, template_path(template) %></td>
             <td><%= link_to template.user.name, user_path(template.user) %></td>
             <td><%= template.avg_rating %></td>
             <td><%= template.created_at.strftime('%B %d, %G') %></td>
             </tr>
            <% end %>


        </tbody>
      </table>

app/views/templates/edit.html.erb
<div class="container">
  <div class="jumbotron">
    <h2>Edit Story</h2>


    <%= image_tag @template.avatar.url(:medium) %>

    <h3><%= @template.title %></h3>
    <p>Story Author: <%= link_to @template.user.name, user_path(@template.user) %></p>
    <p>Cateogry: <%= link_to @template.category, category_path(@template.category) %></p>

    <p>Edit your story below.</p>
  </div
</div>


<% if @template.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@template.errors.count, "error") %>
      prohibited this story from being saved:
    </h2>

    <ul>
    <% @template.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @template, html: { multipart: true } do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :story_template  %><br>
  <%= f.text_area :story_template, cols:80, rows:10 %><br>
  <%= f.label :category %>
  <%= f.select :category,[['Politics', 'Politics'], ['Self Help', 'Self Help'],
  ['Police Blotter','Police Blotter'],['History', 'History'],['How-To', 'How-To'],
  ['Nursery Rhyme', 'Nursery Rhyme']] %> <br><br>

  <%= f.file_field :avatar %>

  <%= f.submit "Update Story" %>
<%end%>

app/views/templates/index.html.erb
<% @templates.each do |each_story|  %>
  <%= link_to each_story.title, template_path(each_story) %>
  <%= each_story.category %>
<% end %>

app/views/templates/new.html.erb
<div class="container">
  <div class="jumbotron" style="background:transparent url(/assets/background.jpg) no-repeat center /cover">
    <h1>Create a New Story</h1>
    <p>Enter a title for your story below. Then write your story in the Story Template field. To select your keywords just write what kind of word you'd like the user to fill in surround by hashtags. For example, "This is my story and I'd like the user to input a #noun_1#." This will prompt the user filling out your madlib with a "Noun:" field. Lastly, select a category your story falls into and then click 'Create Template'.</p>
  </div
</div>


<% if @template.errors.any? %>
  <div id="error_explanation" class="alert alert-danger" role="alert">
    <strong>Oh No!</strong>
    <% @template.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </div>
<% end %>



<%= form_for @template, url: templates_path, html: { multipart: true } do |f| %>
  <h3-f><%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :story_template  %><br>
  <%= f.text_area :story_template, cols:40, rows:10 %><br>
  <%= f.label :category %></h3>
  <%= f.select :category,[['Politics', 'Politics'], ['Self Help', 'Self Help'],
  ['Police Blotter','Police Blotter'],['History', 'History'],['How-To', 'How-To'],
  ['Nursery Rhyme', 'Nursery Rhyme']] %> <br><br>

  <%= f.file_field :avatar %>
<br>
  <%= f.submit "Create New Story" %>
<%end%>

app/views/templates/show.html.erb
<div class="container">
<div class="jumbotron" style="background:transparent url(/assets/background.jpg) no-repeat center /cover">


  <div class="container">
    <div class="row">
      <div class="col-sm-4 "> <%= image_tag @template.avatar.url(:medium) %></div>
      <div class="col-sm-8 ">   <h3><%= @template.title %></h3>
        <p>Story Author: <%= link_to @template.user.name, user_path(@template.user) %></p>
        <p>Cateogry: <%= link_to @template.category, category_path(@template.category) %></p>

        <p>Fill in the blanks with the prompted words. When you finish, submit your story!</p>

        <%= link_to "Edit this Template", edit_template_path(@template) %></div>
    </div>
  </div>


  </div>
</div>


<div class="container">
  <div class="jumbotron" style="background:transparent url(/assets/background.jpg) no-repeat center /cover">
    <div class="container">
      <div class="row">


        <%= form_tag '/completed_stories' do %>
        <% count = 0 %>
          <% @hash.each do |key,value| %>
          <div class="col-sm-3 well text-center">
            <%= label_tag :"#{key}:" %><br>
            <%= text_field_tag :"words[#{key}]" %>
          </div>

          <% count += 1 %>
          <% if count % 3 != 0 %>
            <div class="col-sm-1 text-center"></div>
            <% end %>
              <% end %>

          </div>
            <br><br>
            <%= hidden_field_tag(:template_id, @template.id) %>
            <%= submit_tag "Create Story" %>
        <% end %>







  </div>
</div>

app/views/users/index.html.erb
<h2>All Users</h2>

<% @users.each do |user|  %>
  <%= link_to user.name, user_path(user) %>
<% end %>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation" class="alert alert-danger" role="alert">
    <strong>Oh NO!</strong>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>



  <%= form_for @user, url: users_path, html: { multipart: true} do |f| %>
    <h4><%= f.label :name %></h4>
    <%= f.text_field :name %>
    <h4><%= f.label :password %></h4>
    <%= f.password_field :password %>
    <h4><%= f.label :password_confirmation %></h4>
    <%= f.password_field :password_confirmation %><br><br>
    <%= f.file_field :avatar %><br>
  <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <div class="jumbotron" style="background:transparent url(/assets/background.jpg) no-repeat center /cover">
    <div class="container">
      <div class="row">
        <div class="col-sm-4 text-center"> <%= image_tag @user.avatar.url(:medium) %></div>
        <div class="col-sm-8  text-center"> <h1><%= @user.name %></h1></div>
      </div>
    </div>
  </div>

  <h3>Submitted Stories</h3>
  <br>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">STORY NAME</th>
        <th scope="col">CATEGORY</th>
        <th scope="col">AVERAGE RATING</th>
        <th scope="col">DATE CREATED</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <% @user.templates.each do |template| %>
           <td><%= link_to template.title, template_path(template) %></td>
           <td><%= link_to template.category, category_path(template.category) %></td>
           <td><%= template.avg_rating %></td>
           <td><%= template.created_at.strftime('%B %d, %G') %></td>
      </tr>
        <% end %>
    </tbody>
  </table>

  <br>

  <h3>Completed Stories</h3>
  <br>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">STORY NAME</th>
        <th scope="col">CATEGORY</th>
        <th scope="col">USER RATING</th>
        <th scope="col">DATE CREATED</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <% @user.completed_stories.each do |completed_story| %>
         <td><%= link_to completed_story.template.title, completed_story_path(completed_story) %></td>
         <td><%= completed_story.template.category %></td>
         <td><%= completed_story.temp_rating %></td>
         <td><%= completed_story.created_at.strftime('%B %d, %G') %></td>
         </tr>
        <% end %>
    </tbody>
  </table>
</div>

app/views/welcome/home.html.erb
<div class="container">
  <div class="jumbotron" style="background:transparent url(/assets/background.jpg) no-repeat center /cover">
    <div class="container">
      <div class="row">
        <div class="col-sm-4 text-center"> <%= image_tag @user.avatar.url(:medium) %></div>
        <div class="col-sm-8  text-center">
          <h1>Welcome <%= current_user.name %></h1>
          <br>
          <p>Play madlibs, create your own stories, see other user's stories.</p>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="container">
  <div class="jumbotron">
    <div class="row">
      <div class="col-sm-8 text-right">
        <h2><%= @story_from_pop_temp.template.title %></h2>
        <h4>Category: <%= link_to @story_from_pop_temp.template.category, category_path(@story_from_pop_temp.template.category) %></h4>
        <h4>Written by: <%= link_to @story_from_pop_temp.template.user.name, user_path(@story_from_pop_temp.template.user) %></h4>
        <h4>Filled out by: <%= link_to @story_from_pop_temp.user.name, user_path(@story_from_pop_temp.user) %></h4>

        <p><%= @story_from_pop_temp.finished_story %></p>

        <br>

        <h4><%= link_to 'Play this story!', template_path(@story_from_pop_temp.template) %></h4>

      </div>
      <div class="col-sm-4"><%= image_tag @story_from_pop_temp.template.avatar.url(:medium) %></div>

    </div>
  </div>
</div>